name: lwdframework
description: Lightweight Dart Framework is an api restful framework for dart and flutter developers.
version: 0.3.1
homepage: https://github.com/emirg1989/LWD-Framework

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  meta: ^1.7.0
  path_to_regexp: ^0.4.0

dev_dependencies:
  pedantic: 1.10.0
  test: 1.16.0
